# psql -h localhost -p 25432 -U test -W
version: "3.9"
services:
  postgres:
    image: postgres:15
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    # Persisten data
    # volumes:
    #   - "/tmp/test-db-data:/var/lib/postgresql/data"
